# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NKOtYDZcqJI40-Ca_7xo5wq7oDQvRTWo
"""

import numpy as np
import matplotlib.pyplot as plt


num_points = 100


x = np.random.rand(num_points) * 10  # 0 dan 10 gacha bo'lgan tasodifiy X qiymatlari
y = np.random.rand(num_points) * 10  # 0 dan 10 gacha bo'lgan tasodifiy Y qiymatlari


plt.scatter(x, y)


plt.title('Ixriyotli Nuqtalar Scatter Grafi')
plt.xlabel('X')
plt.ylabel('Y')


plt.grid(True)

plt.show()